/**
 * Generates dist/_headers after the build.
 *
 * The Content-Security-Policy is generated rather than hand-written because it
 * carries a SHA-256 hash for every inline <script> Astro emitted. Hand-writing
 * it would mean either pasting new hashes after every build — which nobody
 * does, so it rots — or falling back to 'unsafe-inline', which is the same as
 * having no script policy at all.
 *
 * Run by `npm run build`.
 */
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');

/** Every .html file in the build, at any depth. */
function pages(dir) {
  const found = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) found.push(...pages(full));
    else if (entry.endsWith('.html')) found.push(full);
  }
  return found;
}

const sha256 = (text) => `'sha256-${createHash('sha256').update(text, 'utf8').digest('base64')}'`;

const scriptHashes = new Set();
const styleHashes = new Set();
let styleAttributes = 0;

for (const page of pages(dist)) {
  const html = readFileSync(page, 'utf8');
  for (const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)) {
    if (/\bsrc=/i.test(match[1])) continue; // external, covered by 'self'
    if (/\btype\s*=\s*["']?application\/(ld\+)?json/i.test(match[1])) continue; // data, not code
    scriptHashes.add(sha256(match[2]));
  }
  for (const match of html.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)) {
    styleHashes.add(sha256(match[1]));
  }
  styleAttributes += (html.match(/\sstyle="/g) ?? []).length;
}

/*
  style-src carries 'unsafe-inline' and script-src deliberately does not.

  Grid and Plate set a custom property through a style attribute — the column
  template and the aspect ratio are per-instance values, not a fixed set — and
  CSP cannot hash an attribute without 'unsafe-hashes'. style-src-attr would be
  exact, but browsers that do not implement it fall back to style-src and would
  strip those attributes, which silently breaks every grid on the page.

  The trade is worth making in this direction: an inline style can restyle the
  page, an inline script can exfiltrate the enquiry form. Scripts stay locked to
  hashes and same-origin, and this site renders no user input into its HTML, so
  there is no injection vector to exploit the style relaxation.
*/
const csp = [
  `default-src 'self'`,
  `script-src 'self' ${[...scriptHashes].join(' ')}`,
  `style-src 'self' 'unsafe-inline'`,
  `img-src 'self' data:`,
  `font-src 'self'`,
  `media-src 'self'`,
  `connect-src 'self'`,
  `form-action 'self'`,
  `frame-ancestors 'none'`,
  `base-uri 'none'`,
  `object-src 'none'`,
  `worker-src 'none'`,
  `manifest-src 'self'`,
  `upgrade-insecure-requests`,
].join('; ');

const YEAR = 60 * 60 * 24 * 365;

const headers = `# Generated by scripts/headers.mjs — do not edit dist/_headers by hand.
# Edit the generator instead; this file is rewritten on every build.

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()
  X-Frame-Options: DENY
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  Content-Security-Policy: ${csp}
  Cache-Control: public, max-age=0, must-revalidate

# Astro hashes these filenames, so the content can never change under a name.
/_astro/*
  Cache-Control: public, max-age=${YEAR}, immutable

# NOTE: font filenames are NOT content-hashed — oswald-500.woff2 keeps its name
# when the subset is rebuilt. Immutable is still right (they change about never)
# but re-running "npm run fonts" means purging the Cloudflare cache, or the edge
# will serve the old subset for a year.
/fonts/*
  Cache-Control: public, max-age=${YEAR}, immutable

# Media names are not hashed either, and unlike fonts these will be re-cut. A
# week is long enough to be free on a repeat visit and short enough that a
# re-encode reaches people without a purge.
/media/*
  Cache-Control: public, max-age=604800

# The API is never cached.
/api/*
  Cache-Control: no-store
`;

writeFileSync(join(dist, '_headers'), headers);

console.log(
  `  _headers written — ${scriptHashes.size} inline script hash(es), ` +
    `${styleHashes.size} inline style block(s), ${styleAttributes} style attribute(s)`
);
